// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpClient is an autogenerated mock type for the HttpClient type
type HttpClient struct {
	mock.Mock
}

type HttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpClient) EXPECT() *HttpClient_Expecter {
	return &HttpClient_Expecter{mock: &_m.Mock}
}

// GetWeatherData provides a mock function with given fields: longitude, latitude
func (_m *HttpClient) GetWeatherData(longitude float64, latitude float64) (string, error) {
	ret := _m.Called(longitude, latitude)

	if len(ret) == 0 {
		panic("no return value specified for GetWeatherData")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, float64) (string, error)); ok {
		return rf(longitude, latitude)
	}
	if rf, ok := ret.Get(0).(func(float64, float64) string); ok {
		r0 = rf(longitude, latitude)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(float64, float64) error); ok {
		r1 = rf(longitude, latitude)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HttpClient_GetWeatherData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeatherData'
type HttpClient_GetWeatherData_Call struct {
	*mock.Call
}

// GetWeatherData is a helper method to define mock.On call
//   - longitude float64
//   - latitude float64
func (_e *HttpClient_Expecter) GetWeatherData(longitude interface{}, latitude interface{}) *HttpClient_GetWeatherData_Call {
	return &HttpClient_GetWeatherData_Call{Call: _e.mock.On("GetWeatherData", longitude, latitude)}
}

func (_c *HttpClient_GetWeatherData_Call) Run(run func(longitude float64, latitude float64)) *HttpClient_GetWeatherData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(float64))
	})
	return _c
}

func (_c *HttpClient_GetWeatherData_Call) Return(_a0 string, _a1 error) *HttpClient_GetWeatherData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HttpClient_GetWeatherData_Call) RunAndReturn(run func(float64, float64) (string, error)) *HttpClient_GetWeatherData_Call {
	_c.Call.Return(run)
	return _c
}

// NewHttpClient creates a new instance of HttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpClient {
	mock := &HttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
